- name: Secure sshd
  ansible.builtin.copy:
    src: files/ssh-secure.conf
    dest: /etc/ssh/sshd_config.d/00-secure.conf
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH

- name: Ensure Firewall is running
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Ensure Rsyslog is not running
  service:
    name: rsyslog
    state: stopped
    enabled: no



# https://www.digitalocean.com/community/tutorial-series/how-to-write-ansible-playbooks
- name: Docker repo
  get_url:
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/docker-ce.repo

# https://docs.rockylinux.org/gemstones/containers/docker/
- name: Install Docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Remove empty dirs
  ansible.builtin.file:
    path: /opt/containerd
    state: absent

- name: Install docker proxy
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  notify: Reload docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create root config directory if it does not exist
  ansible.builtin.file:
    path: "{{ dir_prefix }}"
    state: directory

- name: Create Livekit config directory if it does not exist
  ansible.builtin.file:
    path: "{{ dir_prefix }}/livekit"
    state: directory

# https://www.digitalocean.com/community/tutorials/how-to-create-and-use-templates-in-ansible-playbooks
- name: Create Livekit config
  template:
    src: templates/livekit.yaml.tpl
    dest: "{{ dir_prefix }}/livekit/livekit.yaml"

- name: Create Traefik config directory if it does not exist
  ansible.builtin.file:
    path: "{{ dir_prefix }}/traefik/dynamic"
    state: directory

- name: Create Traefik static config
  template:
    src: templates/traefik.yml.tpl
    dest: "{{ dir_prefix }}/traefik/traefik.yml"

- name: Create Traefik dynamic config
  template:
    src: templates/common_middlewares.yml.tpl
    dest: "{{ dir_prefix }}/traefik/dynamic/common_middlewares.yml"

- name: Create PostgreSQL config directory if it does not exist
  ansible.builtin.file:
    path: "{{ dir_prefix }}/postgresql/docker-entrypoint-initdb.d"
    state: directory

- name: Create PostgreSQL init.sql
  ansible.builtin.copy:
    src: files/init.sql
    dest: "{{ dir_prefix }}/postgresql/docker-entrypoint-initdb.d/init.sql"

- name: Create Egress config directory if it does not exist
  ansible.builtin.file:
    path: "{{ dir_prefix }}/egress"
    state: directory

- name: Create Egress config
  ansible.builtin.copy:
    src: files/egress.yaml
    dest: "{{ dir_prefix }}/egress/config.yaml"

- name: Create Minio data directory and set owner and access on Minio data directory non recursively
  ansible.builtin.file:
    path: /mnt/chat-minio/data
    state: directory
    mode: u=rwx,g-rwx,o-rwx
    # https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/
    # https://github.com/bitnami/containers/blob/main/bitnami/minio/2024/debian-12/Dockerfile#L61C6-L61C10
    owner: 1001
    group: 1001

- name: Create Storage tmp directory if it does not exist
  ansible.builtin.file:
    path: /mnt/chat-storage-tmp
    state: directory
    mode: a=rw

- name: Create PostgreSQL data directory if it does not exist
  ansible.builtin.file:
    path: /mnt/chat-postgresql
    state: directory
    mode: u=rwx,g-rwx,o-rwx
    owner: 70
    group: 70

- name: Create Docker Compose Infra
  template:
    src: templates/docker-compose-infra.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-infra.yml"

- name: Create Docker prune cron
  ansible.builtin.copy:
    src: files/docker-prune.sh
    dest: "/etc/cron.daily/docker-prune.sh"
    mode: a+x

- name: Install python package
  package:
    name:
      - python
      - pip
    state: latest

- name: Install python packages to manipulate with docker swarm
  ansible.builtin.pip:
    name:
      - docker
      - jsondiff

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_swarm_module.html#ansible-collections-community-docker-docker-swarm-module
- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present
  register: swarm_facts

- debug:
    msg: "Swarm tokens are {{ swarm_facts.swarm_facts.JoinTokens }}"

# https://docs.ansible.com/ansible/latest/collections/community/docker/index.html
- name: Deploy stack for Infra
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-infra.yml"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_hash_filter.html
- name: Create Docker Compose AAA
  template:
    src: templates/docker-compose-aaa.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-aaa.yml"
  vars:
    tag: latest

- name: Deploy stack for AAA
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-aaa.yml"

- name: Create Docker Compose Frontend
  template:
    src: templates/docker-compose-frontend.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-frontend.yml"
  vars:
    tag: latest

- name: Deploy stack for Frontend
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-frontend.yml"

- name: Create Docker Compose Chat
  template:
    src: templates/docker-compose-chat.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-chat.yml"
  vars:
    tag: latest

- name: Deploy stack for Chat
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-chat.yml"

- name: Create Docker Compose Storage
  template:
    src: templates/docker-compose-storage.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-storage.yml"
  vars:
    tag: latest

- name: Deploy stack for Storage
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-storage.yml"

- name: Create Docker Compose Video
  template:
    src: templates/docker-compose-video.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-video.yml"
  vars:
    tag: latest

- name: Deploy stack for Video
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-video.yml"

- name: Create Docker Compose Event
  template:
    src: templates/docker-compose-event.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-event.yml"
  vars:
    tag: latest

- name: Deploy stack for Event
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-event.yml"

- name: Create Docker Compose Notification
  template:
    src: templates/docker-compose-notification.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-notification.yml"
  vars:
    tag: latest

- name: Deploy stack for Notification
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-notification.yml"

- name: Create Docker Compose Public
  template:
    src: templates/docker-compose-public.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-public.yml"
  vars:
    tag: latest

- name: Deploy stack for Public
  community.docker.docker_stack:
    state: present
    name: "{{ swarm_stack_name }}"
    compose:
      - "{{ dir_prefix }}/docker-compose-public.yml"


# rest part is set non-deployed tag for deploying without docker hub
- name: Change Docker Compose AAA
  template:
    src: templates/docker-compose-aaa.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-aaa.yml"
  vars:
    tag: changing

- name: Change Docker Compose Frontend
  template:
    src: templates/docker-compose-frontend.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-frontend.yml"
  vars:
    tag: changing

- name: Change Docker Compose Chat
  template:
    src: templates/docker-compose-chat.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-chat.yml"
  vars:
    tag: changing

- name: Change Docker Compose Storage
  template:
    src: templates/docker-compose-storage.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-storage.yml"
  vars:
    tag: changing

- name: Change Docker Compose Video
  template:
    src: templates/docker-compose-video.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-video.yml"
  vars:
    tag: changing

- name: Change Docker Compose Event
  template:
    src: templates/docker-compose-event.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-event.yml"
  vars:
    tag: changing

- name: Change Docker Compose Notification
  template:
    src: templates/docker-compose-notification.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-notification.yml"
  vars:
    tag: changing

- name: Change Docker Compose Public
  template:
    src: templates/docker-compose-public.yml.tpl
    dest: "{{ dir_prefix }}/docker-compose-public.yml"
  vars:
    tag: changing
