// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"
	"nkonev.name/chat/dto"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAaaRestClient creates a new instance of MockAaaRestClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAaaRestClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAaaRestClient {
	mock := &MockAaaRestClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAaaRestClient is an autogenerated mock type for the AaaRestClient type
type MockAaaRestClient struct {
	mock.Mock
}

type MockAaaRestClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAaaRestClient) EXPECT() *MockAaaRestClient_Expecter {
	return &MockAaaRestClient_Expecter{mock: &_m.Mock}
}

// CheckAreUsersExists provides a mock function for the type MockAaaRestClient
func (_mock *MockAaaRestClient) CheckAreUsersExists(ctx context.Context, userIds []int64) ([]dto.UserExists, error) {
	ret := _mock.Called(ctx, userIds)

	if len(ret) == 0 {
		panic("no return value specified for CheckAreUsersExists")
	}

	var r0 []dto.UserExists
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]dto.UserExists, error)); ok {
		return returnFunc(ctx, userIds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []dto.UserExists); ok {
		r0 = returnFunc(ctx, userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserExists)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, userIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAaaRestClient_CheckAreUsersExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAreUsersExists'
type MockAaaRestClient_CheckAreUsersExists_Call struct {
	*mock.Call
}

// CheckAreUsersExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userIds []int64
func (_e *MockAaaRestClient_Expecter) CheckAreUsersExists(ctx interface{}, userIds interface{}) *MockAaaRestClient_CheckAreUsersExists_Call {
	return &MockAaaRestClient_CheckAreUsersExists_Call{Call: _e.mock.On("CheckAreUsersExists", ctx, userIds)}
}

func (_c *MockAaaRestClient_CheckAreUsersExists_Call) Run(run func(ctx context.Context, userIds []int64)) *MockAaaRestClient_CheckAreUsersExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAaaRestClient_CheckAreUsersExists_Call) Return(userExistss []dto.UserExists, err error) *MockAaaRestClient_CheckAreUsersExists_Call {
	_c.Call.Return(userExistss, err)
	return _c
}

func (_c *MockAaaRestClient_CheckAreUsersExists_Call) RunAndReturn(run func(ctx context.Context, userIds []int64) ([]dto.UserExists, error)) *MockAaaRestClient_CheckAreUsersExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetOnlines provides a mock function for the type MockAaaRestClient
func (_mock *MockAaaRestClient) GetOnlines(ctx context.Context, userIds []int64) ([]*dto.UserOnline, error) {
	ret := _mock.Called(ctx, userIds)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlines")
	}

	var r0 []*dto.UserOnline
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]*dto.UserOnline, error)); ok {
		return returnFunc(ctx, userIds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []*dto.UserOnline); ok {
		r0 = returnFunc(ctx, userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.UserOnline)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, userIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAaaRestClient_GetOnlines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnlines'
type MockAaaRestClient_GetOnlines_Call struct {
	*mock.Call
}

// GetOnlines is a helper method to define mock.On call
//   - ctx context.Context
//   - userIds []int64
func (_e *MockAaaRestClient_Expecter) GetOnlines(ctx interface{}, userIds interface{}) *MockAaaRestClient_GetOnlines_Call {
	return &MockAaaRestClient_GetOnlines_Call{Call: _e.mock.On("GetOnlines", ctx, userIds)}
}

func (_c *MockAaaRestClient_GetOnlines_Call) Run(run func(ctx context.Context, userIds []int64)) *MockAaaRestClient_GetOnlines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAaaRestClient_GetOnlines_Call) Return(userOnlines []*dto.UserOnline, err error) *MockAaaRestClient_GetOnlines_Call {
	_c.Call.Return(userOnlines, err)
	return _c
}

func (_c *MockAaaRestClient_GetOnlines_Call) RunAndReturn(run func(ctx context.Context, userIds []int64) ([]*dto.UserOnline, error)) *MockAaaRestClient_GetOnlines_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockAaaRestClient
func (_mock *MockAaaRestClient) GetUsers(ctx context.Context, userIds []int64) ([]*dto.User, error) {
	ret := _mock.Called(ctx, userIds)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*dto.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]*dto.User, error)); ok {
		return returnFunc(ctx, userIds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []*dto.User); ok {
		r0 = returnFunc(ctx, userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, userIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAaaRestClient_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockAaaRestClient_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userIds []int64
func (_e *MockAaaRestClient_Expecter) GetUsers(ctx interface{}, userIds interface{}) *MockAaaRestClient_GetUsers_Call {
	return &MockAaaRestClient_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, userIds)}
}

func (_c *MockAaaRestClient_GetUsers_Call) Run(run func(ctx context.Context, userIds []int64)) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAaaRestClient_GetUsers_Call) Return(users []*dto.User, err error) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockAaaRestClient_GetUsers_Call) RunAndReturn(run func(ctx context.Context, userIds []int64) ([]*dto.User, error)) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchGetUsers provides a mock function for the type MockAaaRestClient
func (_mock *MockAaaRestClient) SearchGetUsers(ctx context.Context, searchString string, including bool, ids []int64, page int64, size int32) ([]*dto.User, int64, error) {
	ret := _mock.Called(ctx, searchString, including, ids, page, size)

	if len(ret) == 0 {
		panic("no return value specified for SearchGetUsers")
	}

	var r0 []*dto.User
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, []int64, int64, int32) ([]*dto.User, int64, error)); ok {
		return returnFunc(ctx, searchString, including, ids, page, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, []int64, int64, int32) []*dto.User); ok {
		r0 = returnFunc(ctx, searchString, including, ids, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, []int64, int64, int32) int64); ok {
		r1 = returnFunc(ctx, searchString, including, ids, page, size)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, bool, []int64, int64, int32) error); ok {
		r2 = returnFunc(ctx, searchString, including, ids, page, size)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAaaRestClient_SearchGetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchGetUsers'
type MockAaaRestClient_SearchGetUsers_Call struct {
	*mock.Call
}

// SearchGetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - searchString string
//   - including bool
//   - ids []int64
//   - page int64
//   - size int32
func (_e *MockAaaRestClient_Expecter) SearchGetUsers(ctx interface{}, searchString interface{}, including interface{}, ids interface{}, page interface{}, size interface{}) *MockAaaRestClient_SearchGetUsers_Call {
	return &MockAaaRestClient_SearchGetUsers_Call{Call: _e.mock.On("SearchGetUsers", ctx, searchString, including, ids, page, size)}
}

func (_c *MockAaaRestClient_SearchGetUsers_Call) Run(run func(ctx context.Context, searchString string, including bool, ids []int64, page int64, size int32)) *MockAaaRestClient_SearchGetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 []int64
		if args[3] != nil {
			arg3 = args[3].([]int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int32
		if args[5] != nil {
			arg5 = args[5].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAaaRestClient_SearchGetUsers_Call) Return(users []*dto.User, n int64, err error) *MockAaaRestClient_SearchGetUsers_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *MockAaaRestClient_SearchGetUsers_Call) RunAndReturn(run func(ctx context.Context, searchString string, including bool, ids []int64, page int64, size int32) ([]*dto.User, int64, error)) *MockAaaRestClient_SearchGetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatCreateOption creates a new instance of MockChatCreateOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatCreateOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatCreateOption {
	mock := &MockChatCreateOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatCreateOption is an autogenerated mock type for the ChatCreateOption type
type MockChatCreateOption struct {
	mock.Mock
}

type MockChatCreateOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatCreateOption) EXPECT() *MockChatCreateOption_Expecter {
	return &MockChatCreateOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockChatCreateOption
func (_mock *MockChatCreateOption) Apply(createDto *dto.ChatBaseCreateDto) {
	_mock.Called(createDto)
	return
}

// MockChatCreateOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockChatCreateOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - createDto *dto.ChatBaseCreateDto
func (_e *MockChatCreateOption_Expecter) Apply(createDto interface{}) *MockChatCreateOption_Apply_Call {
	return &MockChatCreateOption_Apply_Call{Call: _e.mock.On("Apply", createDto)}
}

func (_c *MockChatCreateOption_Apply_Call) Run(run func(createDto *dto.ChatBaseCreateDto)) *MockChatCreateOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.ChatBaseCreateDto
		if args[0] != nil {
			arg0 = args[0].(*dto.ChatBaseCreateDto)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatCreateOption_Apply_Call) Return() *MockChatCreateOption_Apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatCreateOption_Apply_Call) RunAndReturn(run func(createDto *dto.ChatBaseCreateDto)) *MockChatCreateOption_Apply_Call {
	_c.Run(run)
	return _c
}

// NewMockChatGetOption creates a new instance of MockChatGetOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatGetOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatGetOption {
	mock := &MockChatGetOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatGetOption is an autogenerated mock type for the ChatGetOption type
type MockChatGetOption struct {
	mock.Mock
}

type MockChatGetOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatGetOption) EXPECT() *MockChatGetOption_Expecter {
	return &MockChatGetOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockChatGetOption
func (_mock *MockChatGetOption) Apply(queryParams *url.Values) *url.Values {
	ret := _mock.Called(queryParams)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *url.Values
	if returnFunc, ok := ret.Get(0).(func(*url.Values) *url.Values); ok {
		r0 = returnFunc(queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.Values)
		}
	}
	return r0
}

// MockChatGetOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockChatGetOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - queryParams *url.Values
func (_e *MockChatGetOption_Expecter) Apply(queryParams interface{}) *MockChatGetOption_Apply_Call {
	return &MockChatGetOption_Apply_Call{Call: _e.mock.On("Apply", queryParams)}
}

func (_c *MockChatGetOption_Apply_Call) Run(run func(queryParams *url.Values)) *MockChatGetOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.Values
		if args[0] != nil {
			arg0 = args[0].(*url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatGetOption_Apply_Call) Return(values *url.Values) *MockChatGetOption_Apply_Call {
	_c.Call.Return(values)
	return _c
}

func (_c *MockChatGetOption_Apply_Call) RunAndReturn(run func(queryParams *url.Values) *url.Values) *MockChatGetOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageCreateOption creates a new instance of MockMessageCreateOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageCreateOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageCreateOption {
	mock := &MockMessageCreateOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageCreateOption is an autogenerated mock type for the MessageCreateOption type
type MockMessageCreateOption struct {
	mock.Mock
}

type MockMessageCreateOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageCreateOption) EXPECT() *MockMessageCreateOption_Expecter {
	return &MockMessageCreateOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockMessageCreateOption
func (_mock *MockMessageCreateOption) Apply(messageCreateDto *dto.MessageCreateDto) {
	_mock.Called(messageCreateDto)
	return
}

// MockMessageCreateOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockMessageCreateOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - messageCreateDto *dto.MessageCreateDto
func (_e *MockMessageCreateOption_Expecter) Apply(messageCreateDto interface{}) *MockMessageCreateOption_Apply_Call {
	return &MockMessageCreateOption_Apply_Call{Call: _e.mock.On("Apply", messageCreateDto)}
}

func (_c *MockMessageCreateOption_Apply_Call) Run(run func(messageCreateDto *dto.MessageCreateDto)) *MockMessageCreateOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.MessageCreateDto
		if args[0] != nil {
			arg0 = args[0].(*dto.MessageCreateDto)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageCreateOption_Apply_Call) Return() *MockMessageCreateOption_Apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMessageCreateOption_Apply_Call) RunAndReturn(run func(messageCreateDto *dto.MessageCreateDto)) *MockMessageCreateOption_Apply_Call {
	_c.Run(run)
	return _c
}

// NewMockMessagePinnedGetOption creates a new instance of MockMessagePinnedGetOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagePinnedGetOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagePinnedGetOption {
	mock := &MockMessagePinnedGetOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagePinnedGetOption is an autogenerated mock type for the MessagePinnedGetOption type
type MockMessagePinnedGetOption struct {
	mock.Mock
}

type MockMessagePinnedGetOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagePinnedGetOption) EXPECT() *MockMessagePinnedGetOption_Expecter {
	return &MockMessagePinnedGetOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockMessagePinnedGetOption
func (_mock *MockMessagePinnedGetOption) Apply(queryParams *url.Values) *url.Values {
	ret := _mock.Called(queryParams)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *url.Values
	if returnFunc, ok := ret.Get(0).(func(*url.Values) *url.Values); ok {
		r0 = returnFunc(queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.Values)
		}
	}
	return r0
}

// MockMessagePinnedGetOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockMessagePinnedGetOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - queryParams *url.Values
func (_e *MockMessagePinnedGetOption_Expecter) Apply(queryParams interface{}) *MockMessagePinnedGetOption_Apply_Call {
	return &MockMessagePinnedGetOption_Apply_Call{Call: _e.mock.On("Apply", queryParams)}
}

func (_c *MockMessagePinnedGetOption_Apply_Call) Run(run func(queryParams *url.Values)) *MockMessagePinnedGetOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.Values
		if args[0] != nil {
			arg0 = args[0].(*url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessagePinnedGetOption_Apply_Call) Return(values *url.Values) *MockMessagePinnedGetOption_Apply_Call {
	_c.Call.Return(values)
	return _c
}

func (_c *MockMessagePinnedGetOption_Apply_Call) RunAndReturn(run func(queryParams *url.Values) *url.Values) *MockMessagePinnedGetOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageGetOption creates a new instance of MockMessageGetOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageGetOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageGetOption {
	mock := &MockMessageGetOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageGetOption is an autogenerated mock type for the MessageGetOption type
type MockMessageGetOption struct {
	mock.Mock
}

type MockMessageGetOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageGetOption) EXPECT() *MockMessageGetOption_Expecter {
	return &MockMessageGetOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockMessageGetOption
func (_mock *MockMessageGetOption) Apply(queryParams *url.Values) *url.Values {
	ret := _mock.Called(queryParams)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *url.Values
	if returnFunc, ok := ret.Get(0).(func(*url.Values) *url.Values); ok {
		r0 = returnFunc(queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.Values)
		}
	}
	return r0
}

// MockMessageGetOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockMessageGetOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - queryParams *url.Values
func (_e *MockMessageGetOption_Expecter) Apply(queryParams interface{}) *MockMessageGetOption_Apply_Call {
	return &MockMessageGetOption_Apply_Call{Call: _e.mock.On("Apply", queryParams)}
}

func (_c *MockMessageGetOption_Apply_Call) Run(run func(queryParams *url.Values)) *MockMessageGetOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.Values
		if args[0] != nil {
			arg0 = args[0].(*url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageGetOption_Apply_Call) Return(values *url.Values) *MockMessageGetOption_Apply_Call {
	_c.Call.Return(values)
	return _c
}

func (_c *MockMessageGetOption_Apply_Call) RunAndReturn(run func(queryParams *url.Values) *url.Values) *MockMessageGetOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParticipantGetOption creates a new instance of MockParticipantGetOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantGetOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantGetOption {
	mock := &MockParticipantGetOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParticipantGetOption is an autogenerated mock type for the ParticipantGetOption type
type MockParticipantGetOption struct {
	mock.Mock
}

type MockParticipantGetOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParticipantGetOption) EXPECT() *MockParticipantGetOption_Expecter {
	return &MockParticipantGetOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockParticipantGetOption
func (_mock *MockParticipantGetOption) Apply(queryParams *url.Values) *url.Values {
	ret := _mock.Called(queryParams)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *url.Values
	if returnFunc, ok := ret.Get(0).(func(*url.Values) *url.Values); ok {
		r0 = returnFunc(queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.Values)
		}
	}
	return r0
}

// MockParticipantGetOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockParticipantGetOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - queryParams *url.Values
func (_e *MockParticipantGetOption_Expecter) Apply(queryParams interface{}) *MockParticipantGetOption_Apply_Call {
	return &MockParticipantGetOption_Apply_Call{Call: _e.mock.On("Apply", queryParams)}
}

func (_c *MockParticipantGetOption_Apply_Call) Run(run func(queryParams *url.Values)) *MockParticipantGetOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.Values
		if args[0] != nil {
			arg0 = args[0].(*url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParticipantGetOption_Apply_Call) Return(values *url.Values) *MockParticipantGetOption_Apply_Call {
	_c.Call.Return(values)
	return _c
}

func (_c *MockParticipantGetOption_Apply_Call) RunAndReturn(run func(queryParams *url.Values) *url.Values) *MockParticipantGetOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}
