version: '3.7'

services:
  seo:
    image: nkonev/chat-seo:changing
    networks:
      backend:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.seo-service.loadbalancer.server.port=3100"

        - "traefik.http.routers.seo-router-blog-ssr.rule=PathPrefix(`/blog`) && HeadersRegexp(`User-Agent`, `(?i)(Go-|bot|yandex|google)`)"
        - "traefik.http.routers.seo-router-blog-ssr.entrypoints=http"
        - "traefik.http.routers.seo-router-blog-ssr.middlewares=retry-middleware@file"

        - "traefik.http.routers.seo-router-robots.rule=Path(`/robots.txt`)"
        - "traefik.http.routers.seo-router-robots.entrypoints=http"
        - "traefik.http.routers.seo-router-robots.middlewares=retry-middleware@file"

        - "traefik.http.routers.seo-router-sitemap.rule=Path(`/sitemap.xml`)"
        - "traefik.http.routers.seo-router-sitemap.entrypoints=http"
        - "traefik.http.routers.seo-router-sitemap.middlewares=retry-middleware@file"

        - "traefik.http.middlewares.seo-stripprefix-middleware.stripprefix.prefixes=/seo"
        - "traefik.http.routers.seo-version-router.rule=Path(`/seo/git.json`)"
        - "traefik.http.routers.seo-version-router.entrypoints=http"
        - "traefik.http.routers.seo-version-router.middlewares=seo-stripprefix-middleware"

    environment:
      - CHAT_API_URL=http://chat:1235
      - FRONTEND_URL=http://api.site.local:8080

    logging:
      driver: "journald"
      options:
        tag: chat-seo

networks:
  backend:
    driver: overlay
