<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AAA</title>
</head>

<body>
    <div id="app-container">
        <#include "header.ftlh">
        <h1>Welcome to AAA</h1>

        <a href="/oauth2.html">OAuth2 test page</a>
        <a href="/login.html">Login page</a>

    </div>
</body>
</html>