// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type DisplayMessageDto struct {
	ID             int64      `json:"id"`
	Text           string     `json:"text"`
	ChatID         int64      `json:"chatId"`
	OwnerID        int64      `json:"ownerId"`
	CreateDateTime time.Time  `json:"createDateTime"`
	EditDateTime   *time.Time `json:"editDateTime"`
	Owner          *User      `json:"owner"`
	CanEdit        bool       `json:"canEdit"`
	FileItemUUID   *uuid.UUID `json:"fileItemUuid"`
}

type MessageNotify struct {
	EventType           *string            `json:"eventType"`
	MessageNotification *DisplayMessageDto `json:"messageNotification"`
}

type User struct {
	ID     int64   `json:"id"`
	Login  string  `json:"login"`
	Avatar *string `json:"avatar"`
}
