// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"nkonev.name/chat/types"
)

type DisplayMessageDto struct {
	ID             int64       `json:"id"`
	Text           string      `json:"text"`
	ChatID         int64       `json:"chatId"`
	OwnerID        int64       `json:"ownerId"`
	CreateDateTime *time.Time  `json:"createDateTime"`
	EditDateTime   *time.Time  `json:"editDateTime"`
	Owner          *User       `json:"owner"`
	CanEdit        bool        `json:"canEdit"`
	FileItemUUID   *types.UUID `json:"fileItemUuid"`
}

type MessageNotify struct {
	Type                *string            `json:"Type"`
	MessageNotification *DisplayMessageDto `json:"MessageNotification"`
}

type User struct {
	ID     int64   `json:"id"`
	Login  string  `json:"login"`
	Avatar *string `json:"avatar"`
}
