import Vue from 'vue';
export default new Vue();
export const LOGGED_OUT = "loggedOut";
export const LOGGED_IN = "loggedIn";
export const CHAT_ADD = "chatAdd";
export const CHAT_EDITED = "chatEdited";
export const CHAT_DELETED = "chatDeleted";
export const OPEN_CHAT_EDIT = "openChatEdit";
export const OPEN_SIMPLE_MODAL = "openSimpleModal";
export const CLOSE_SIMPLE_MODAL = "closeSimpleModal";
export const CHAT_SEARCH_CHANGED = "chatSearchChanged";
export const CHANGE_TITLE = "changeTitle";
export const CHANGE_PHONE_BUTTON = "changePhoneButton";
export const MESSAGE_ADD = "messageAdd";
export const MESSAGE_DELETED = "messageDeleted";
export const MESSAGE_EDITED = "messageEdited";
export const SET_EDIT_MESSAGE = "setEditMessageDto";
export const UNREAD_MESSAGES_CHANGED = "unreadMessagesChanged";
export const VIDEO_LOCAL_ESTABLISHED = "videoLocalEstablished";
export const USER_TYPING = "userTyping";
export const OPEN_CHOOSE_AVATAR = "openChooseAvatar";
export const USER_PROFILE_CHANGED = "userProfileChanged";
export const CHANGE_WEBSOCKET_STATUS = "changeWebsocket";
export const OPEN_INFO_DIALOG = "openInfo";
export const VIDEO_CALL_CHANGED = "videoCallChanged";
export const VIDEO_CALL_INVITED = "videoCallInvited";
