import Vue from 'vue';
export default new Vue();
export const UNAUTHORIZED  = 'unauthorized';
export const LOGGED_OUT = "loggedOut";
export const LOGGED_IN = "loggedIn";
export const CHAT_ADD = "chatAdd";
export const CHAT_EDITED = "chatEdited";
export const CHAT_DELETED = "chatDeleted";
export const OPEN_CHAT_EDIT = "openChatEdit";
export const CHAT_SEARCH_CHANGED = "chatSearchChanged";
