[SERVICE]
    log_level debug
    Parsers_File parsers.conf

[INPUT]
    Name forward
    Unix_Path /var/run/fluent-bit/socket
    Unix_Perm 0777

[INPUT]
    Name tail
    path /var/log/videochat/aaa/logs/*.log
    Tag videochat.app.aaa

[INPUT]
    Name tail
    path /var/log/videochat/chat/logs/*.log
    Tag videochat.app.chat

[INPUT]
    Name tail
    path /var/log/videochat/public/logs/*.log
    Tag videochat.app.public

# for debug purposes
# [FILTER]
#     Name  stdout
#     Match *

[FILTER]
    Name parser
    Match videochat.app.*
    Parser just_json
    Reserve_Data on
    Key_Name log

[FILTER]
    Name parser
    Match videochat.infra.traefik
    Parser just_json
    Reserve_Data on
    Key_Name log

[FILTER]
    Name modify
    Match videochat.infra.traefik
    Rename msg message
    Rename TraceId trace_id
    Rename SpanId span_id
    Rename StartLocal timestamp
    Rename request_User-Agent user_agent
    Add service traefik

[OUTPUT]
    Name stdout
    Match **
